server:
  port: 8080
spring:
#  datasource:
#    username: testuser
#    password: test123
#    url: jdbc:postgresql://localhost:5432/postgres
  redis:
    host: localhost
    port: 6379
    password: test123
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}